### ISSUE TITLE
Where to find "ensemble_location" and "pairwise_rdc_path" for new databases?

### ISSUE THREAD

**Issue by Issam28** [wuziniu/BayesCard#3]
I wanted to test BayesCard against a new database, but I couldn't effectively evaluate it because it needs these two files "_ensemble_location_" and "_pairwise_rdc_path_". Any ideas on how to generate them?

**Comment by wuziniu** [comment]
Hi, please check out the advanced branch. It contains scripts to generate these files.

**Comment by Issam28** [comment]
Hi, thanks for the quick reply. I will check them out.
